src/java/uca/sed360/managedBeans/PeriodoController.java
package uca.sed360.managedBeans;

import uca.sed360.jpaEntities.Periodo;
import uca.sed360.managedBeans.util.JsfUtil;
import uca.sed360.ejbs.PeriodoFacade;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import uca.sed360.jpaEntities.AsignacionMetodologia;
import uca.sed360.jpaEntities.AsignacionMetodologiaPK;
import uca.sed360.jpaEntities.CatalogoMetodologias;
import uca.sed360.jpaEntities.Niveles;
import uca.sed360.jpaEntities.PlanEstrategico;
import uca.sed360.managedBeans.util.SeguimientoController;
import uca.sed360.managedBeans.util.reportes.ReportesUtil;

/**
 * Controlador que maneja los periodos de evaluación
 * @author Estacion 2
 */
@ManagedBean(name = "periodoController")
@SessionScoped
public class PeriodoController implements Serializable {
    
    @ManagedProperty(value="#{planEstrategicoController}")
    private PlanEstrategicoController planMB;
    
    @ManagedProperty(value="#{nivelesController}")
    private NivelesController nivelesMB;
    
    @ManagedProperty(value="#{seguimientoController}")
    private SeguimientoController seguimientoController;
    
    @ManagedProperty(value = "#{auditoriaController}")
    private AuditoriaController audiController;
    
    private Periodo current;
    /**
     *
     */
    public  List<Periodo> listaPeriodos;
    private Periodo periodoVigente;
    private boolean currentHasEvaluaciones;
    private String metodologia;
    private boolean renderDefPanel;
    private boolean hayPeriodoVigente;
    private List<AsignacionMetodologia> listaAsignacionesMetodologia;
    private List<String> listaMetodologiasCombo,listaMetodologiasOneButton;
    ReportesUtil ru = new ReportesUtil();
   
    @EJB
    private uca.sed360.ejbs.PeriodoFacade ejbFacade;   
    @EJB
    private uca.sed360.ejbs.EvaluacionFacade ejbEvaluaciones;
              
    
    /**
     * Constructor
     */
    public PeriodoController() {
    }

    /**
     *
     * @return
     */
    public PlanEstrategicoController getPlanMB() {
        return planMB;
    }

    /**
     *
     * @param planMB
     */
    public void setPlanMB(PlanEstrategicoController planMB) {
        this.planMB = planMB;
    }

    /**
     *
     * @return
     */
    public NivelesController getNivelesMB() {
        return nivelesMB;
    }

    /**
     *
     * @param nivelesMB
     */
    public void setNivelesMB(NivelesController nivelesMB) {
        this.nivelesMB = nivelesMB;
    }

    /**
     *
     * @return
     */
    public SeguimientoController getSeguimientoController() {
        return seguimientoController;
    }

    /**
     *
     * @param seguimientoController
     */
    public void setSeguimientoController(SeguimientoController seguimientoController) {
        this.seguimientoController = seguimientoController;
    }

    /**
     *
     * @return
     */
    public Periodo getPeriodoVigente() {       
        periodoVigente=getFacade().getPeriodoVigente();       
        return periodoVigente;
    }

    /**
     *
     * @param periodoVigente
     */
    public void setPeriodoVigente(Periodo periodoVigente) {
        this.periodoVigente = periodoVigente;
    }
       
    
    /**
     * Comprueba si existe un periodo de evaluación activo o vigente
     * @return verdadero o falso
     */
    public boolean isHayPeriodoVigente() {  
        hayPeriodoVigente=getFacade().hayPeriodoVigente();
        return hayPeriodoVigente;
    }
    
    //getter y setter Lista Asignaciones de Metodologia

    /**
     *
     * @return
     */
    public List<AsignacionMetodologia> getListaAsignacionesMetodologia() {
        return listaAsignacionesMetodologia;
    }

    /**
     *
     * @param listaAsignacionesMetodologia
     */
    public void setListaAsignacionesMetodologia(List<AsignacionMetodologia> listaAsignacionesMetodologia) {
        this.listaAsignacionesMetodologia = listaAsignacionesMetodologia;
    }

    /**
     *
     * @return
     */
    public boolean existenEvaluacionesEnPeriodoSeleccionado(){
        return ejbEvaluaciones.existEvaluacionesPeriodo(current);
    }
    //getter y setter propiedad metodologia (que selecciona el usuario en la interfaz)
    /**
     *
     * @return
     */
    public String getMetodologia() {
        return metodologia;
    }

    /**
     *
     * @param metodologia
     */
    public void setMetodologia(String metodologia) {
        this.metodologia = metodologia;   
    }
    
    
    
    //getter renderDefPanel
    /**
     *
     * @return
     */
    public boolean isRenderDefPanel() {
       if(metodologia.equals(CatalogoMetodologias.METODOLOGIA_HIBRIDA))
            renderDefPanel=true;
        else
            renderDefPanel=false;
        return renderDefPanel;
    }
    
    //getter lista metodologias (utilizado para posibles opciones de metodologia)
    /**
     *
     * @return
     */
    public List<String> getListaMetodologiasCombo() {
        if(listaMetodologiasCombo==null)
            listaMetodologiasCombo=CatalogoMetodologias.getListaMetologias();
        return listaMetodologiasCombo;
    }

    /**
     *
     * @return
     */
    public List<String> getListaMetodologiasOneButton() {
        if(listaMetodologiasOneButton==null){
            listaMetodologiasOneButton = new ArrayList<String>();
            listaMetodologiasOneButton.add(CatalogoMetodologias.METODOLOGIA_180);
            listaMetodologiasOneButton.add(CatalogoMetodologias.METODOLOGIA_360);
        }
        return listaMetodologiasOneButton;
    }
        

    // Periodo de Evaluación ---------------------------------
    /**
     * Comprueba si hay evaluaciones en el periodo actual seleccionado
     * @return
     */
    public boolean isCurrentHasEvaluaciones() {
        return currentHasEvaluaciones;
    }

    /**
     *
     * @param currentHasEvaluaciones
     */
    public void setCurrentHasEvaluaciones(boolean currentHasEvaluaciones) {
        this.currentHasEvaluaciones = currentHasEvaluaciones;
    }
    
    /**
     * Obtiene la metodología de evaluación aplicada al periodo seleccionado
     * @param p
     * @return 180, 360 o hibrida
     */
    public String getMetodologiaPeriodo(Periodo p){
        boolean met180=false,met360=false;
        
        for(AsignacionMetodologia am: p.getAsignacionMetodologiaList()){
               if (am.getMetodologia().equals(CatalogoMetodologias.METODOLOGIA_180)) {
                   met180=true;
                  }
               else if (am.getMetodologia().equals(CatalogoMetodologias.METODOLOGIA_360)) {
                   met360=true;                   
           }  
        }
        if(met180 && met360)
            return CatalogoMetodologias.METODOLOGIA_HIBRIDA;
        else if(met180)
                return CatalogoMetodologias.METODOLOGIA_180;
             else 
                return CatalogoMetodologias.METODOLOGIA_360;
    }
    
    /**
     *
     * @return
     */
    public Periodo getSelected() {
        if (current == null) {
            current = new Periodo();
        }
        return current;
    }
    
    /**
     *
     * @param current
     */
    public void setSelected(Periodo current) {
        this.current = current;
        this.currentHasEvaluaciones=ejbEvaluaciones.existEvaluacionesPeriodo(current);
    }
    
    private PeriodoFacade getFacade() {
        return ejbFacade;
    }

    /**
     *
     * @return
     */
    public List<Periodo> getListaPeriodos() {
        if(listaPeriodos==null)
          listaPeriodos = getFacade().findAll();
        return listaPeriodos;
    }

    /**
     *
     * @param listaPeriodos
     */
    public void setListaPeriodos(List<Periodo> listaPeriodos) {
        this.listaPeriodos = listaPeriodos;
    }
    /**
     *
     * @return
     */
    public String prepareView(){
        metodologia=getMetodologiaPeriodo(current);
        return "DetallePeriodo?faces-redirect=true";
    }
    
    /**
     *
     * @return
     */
    public String prepareCreate() {
        current = new Periodo();
        renderDefPanel=false;
        metodologia=CatalogoMetodologias.METODOLOGIA_360;
        listaAsignacionesMetodologia=new ArrayList<AsignacionMetodologia>();
        for(Niveles n: nivelesMB.getListaNiveles()){
            AsignacionMetodologia am=new AsignacionMetodologia();
            am.setNiveles(n);
            am.setPeriodo(current);    
            listaAsignacionesMetodologia.add(am);
        }
        return "CrearPeriodo?faces-redirect=true";
    }

    /**
     *
     * @return
     */
    public String create() {
        //Validando que exista un Plan Estratégico Vigente
        PlanEstrategico planVigente=planMB.getPlanVigente();
        SimpleDateFormat df=new SimpleDateFormat("dd/MM/yyyy HH:MM");
        if (planVigente != null) {
            if(current.getFechaFin().after(current.getFechaInicio())){
               
                if(current.getFechaInicio().getYear() >= planVigente.getFechaInicio().getYear() && current.getFechaFin().getYear() <= planVigente.getFechaFin().getYear() ) {
                       Periodo peConflictivo = ejbFacade.findByFechas(current);
                       if(peConflictivo == null) {    

src/java/uca/sed360/managedBeans/UtilMB.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package uca.sed360.managedBeans;

import java.util.Date;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 * Controlador auxiliar para la sesión de usuario
 * @author Jose
 */
@ManagedBean
@SessionScoped
public class UtilMB {

    private int indexMenu=0;
    private boolean esNica = true;
    /**
     * Creates a new instance of UtilMB
     */
    public UtilMB() {
    }
    
    /**
     * 
     * @return
     */
    public Date getToday(){
        return new Date();
    }
    

    /**
     *
     * @return
     */
    public int getIndexMenu() {
        return indexMenu;
    }

    /**
     *
     * @param indexMenu
     */
    public void setIndexMenu(int indexMenu) {
        this.indexMenu = indexMenu;
    }

    /**
     *
     * @return
     */
    public boolean isEsNica() {
        return esNica;
    }

    /**
     *
     * @param esNica
     */
    public void setEsNica(boolean esNica) {
        this.esNica = esNica;
    }
    
    
    
    }

    

web/periodo/CrearPeriodo.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://java.sun.com/jsp/jstl/core">

    <ui:composition template="/template.xhtml">
      <ui:define name="title">
              Nuevo Periodo de Evaluación
        </ui:define> 
        <ui:define name="sidebar">
            <ui:include src="_sideBarPeriodo.xhtml"/>
        </ui:define>
        <ui:define name="headerContent">
            <div class="floatRight">
                  <p:commandButton icon="ui-icon-disk" onclick="guardar()"  value="Guardar"   />
                  <p:commandButton icon="ui-icon-seek-prev" action="ListaPeriodos?faces-redirect=true" value="Regresar a lista de periodos"   />                     
            </div>
        </ui:define>
        <ui:define name="body">            
            <h:form id="mainForm">  
                <p:messages id="mensajes"/>
                <h:panelGrid styleClass="noSeleccionable" columns="2" width="70%" columnClasses="colNivel,colMetod">
                    <h:outputLabel value="Descripción" for="descripcion" />
                    <p:inputTextarea autoResize="false"  cols="35" rows="1" style="width: 100%;margin-bottom: 10px !important;" id="descripcion" value="#{periodoController.selected.descripcion}" title="Descripción" required="true" requiredMessage="Debe añadir una descripción para el periodo"/>
                    <h:outputLabel value="Fecha de Inicio" for="fechaInicio" />                    
                    <p:calendar mindate="#{utilMB.today}" id="fechaInicio" pattern="dd/MM/yyyy" value="#{periodoController.selected.fechaInicio}" title="Fecha de Inicio" required="true" requiredMessage="Debe establecer una fecha de inicio para el periodo " />   
                    <h:outputLabel value="Fecha Final" for="fechaFin" />                    
                    <p:calendar id="fechaFin" mindate="#{utilMB.today}" value="#{periodoController.selected.fechaFin}" title="Fecha Fin" required="true" requiredMessage="Debe establecer una fecha final para el periodo " pattern="dd/MM/yyyy" />
                    <h:outputLabel value="Metodología a aplicar" for="metodologia" />
                    <p:selectOneMenu id="metodologia" immediate="true"  value="#{periodoController.metodologia}" >
                        <f:selectItems value="#{periodoController.listaMetodologiasCombo}" var="met"  itemValue="#{met}" itemLabel="#{met}"/>                      
                        <p:ajax  event="change"/>
                    </p:selectOneMenu>
                </h:panelGrid>
                <p:outputPanel id="defPanel"  autoUpdate="true"    >
                    <br/>
                    <p:panel header="Definición  de Metodología por nivel de empleado" style="width: 70%" rendered="#{periodoController.renderDefPanel}">
                        <h:panelGrid columns="2" style="width: 100%" rules="rows" columnClasses="colNivel,colMetod">
                            <h:outputText value="Nivel" styleClass="lead"/>
                            <h:outputText value="Metodología a aplicar" styleClass="lead"/>
                            <c:forEach items="#{periodoController.listaAsignacionesMetodologia}" var="am" varStatus="status" >
                                <h:outputText value="#{am.niveles.descripcion}"/>
                                <p:selectOneButton value="#{am.metodologia}" required="true" requiredMessage="Debe seleccionar un tipo de metodologia para el nivel #{am.niveles.descripcion}">
                                    <f:selectItems value="#{periodoController.listaMetodologiasOneButton}" var="metod" itemValue="#{metod}" itemLabel="#{metod}"/>
                                </p:selectOneButton>
                            </c:forEach>
                        </h:panelGrid>
                    </p:panel>                    
                </p:outputPanel>
                <br/>
                <p:remoteCommand name="guardar" action="#{periodoController.create}" update=":mainForm"/>
               
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/periodo/DetallePeriodo.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://java.sun.com/jsp/jstl/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="Detalle del periodo: #{periodoController.selected.idPeriodo} "></h:outputText>
        </ui:define>
        <ui:define name="sidebar">
            <ui:include src="/periodo/_sideBarPeriodo.xhtml"/>
        </ui:define>
        <ui:define name="headerContent">
             <div class="floatRight">
                    <p:commandButton value="Editar Periodo" action="#{periodoController.prepareUpdate()}"/>
                    <p:commandButton action="ListaPeriodos?faces-redirect=true" value="Ver lista de periodos"/>
              </div>
        </ui:define>
        <ui:define name="body">
            <p:messages autoUpdate="true" />
            <h:form>
                <p:panel header="Información general" style="width: 70%">
                    <h:panelGrid columns="2" style="width: 100%" columnClasses="colNivel,colMetod">
                        <h:outputText value="Descripcion"/>
                        <h:outputText value="#{periodoController.selected.descripcion}" title="Descripción"/>
                        <h:outputText  value="Fecha de Inicio"/>
                        <h:outputText value="#{periodoController.selected.fechaInicio}" title="Fecha de Inicio">
                            <f:convertDateTime pattern="dd/MM/yyyy" />
                        </h:outputText>
                        <h:outputText value="Fecha Final"/>
                        <h:outputText value="#{periodoController.selected.fechaFin}" title="Fecha Fin">
                            <f:convertDateTime pattern="dd/MM/yyyy" />
                        </h:outputText>
                         <h:outputText value="Metodología Aplicada"/>
                         <h:outputText value="#{periodoController.getMetodologiaPeriodo(periodoController.selected)}"/>
                      </h:panelGrid>
                </p:panel>
                <p:panel header="Detalle de Asignación de Metodología por Nivel" style="width: 70%" rendered="#{periodoController.renderDefPanel}">
                     <h:panelGrid columns="2" style="width: 100%" columnClasses="colNivel,colMetod" rules="rows"  >
                            <c:forEach items="#{periodoController.selected.asignacionMetodologiaList}" var="am" varStatus="status" >
                                <h:outputText value="#{am.niveles.descripcion}"/>
                                <h:outputText value="#{am.metodologia}"/>
                            </c:forEach>
                        </h:panelGrid>
                </p:panel>  
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/periodo/EditarPeriodo.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://java.sun.com/jsp/jstl/core">

    <ui:composition template="/template.xhtml">
      <ui:define name="title">
          Editar Periodo de Evaluacion #{periodoController.selected.idPeriodo}
        </ui:define> 
        <ui:define name="sidebar">            
            <ui:include src="_sideBarPeriodo.xhtml"/>
        </ui:define>
        <ui:define name="headerContent">
            <div class="floatRight">
                <p:commandButton  value="Guardar" onclick="guardar()"  />
                <p:commandButton action="ListaPeriodos?faces-redirect=true" value="Regresar a la Lista de Periodos" /> 
                
            </div>
        </ui:define>
        <ui:define name="body">            
            <h:form id="mainForm">  
                <c:set var="existenEvaluaciones" value="#{periodoController.existenEvaluacionesEnPeriodoSeleccionado()}"/>
                <h:panelGroup rendered="#{existenEvaluaciones}">
                    <div class="alert alert-warnig">
                        <div class="lead">Algunos campos no pueden ser editados porque existen evaluaciones realizadas en este periodo.</div>
                    </div>
                </h:panelGroup>
                <p:messages id="mensajes"/>
                <h:panelGrid styleClass="noSeleccionable" columns="2" width="70%" columnClasses="colNivel,colMetod">
                    <h:outputLabel value="Descripción" for="descripcion" />
                    <p:inputTextarea  cols="35" rows="1" style="width: 100%" id="descripcion" value="#{periodoController.selected.descripcion}" title="Descripción" required="true" requiredMessage="Debe añadir una descripción para el periodo"/>
                    <h:outputLabel value="Fecha de Inicio" for="fechaInicio" />                    
                    <p:calendar disabled="#{existenEvaluaciones}" mindate="#{utilMB.today}" id="fechaInicio" pattern="dd/MM/yyyy" value="#{periodoController.selected.fechaInicio}" title="Fecha de Inicio" required="true" requiredMessage="Debe establecer una fecha de inicio para el periodo " />   
                    <h:outputLabel value="Fecha Final" for="fechaFin" />                    
                    <p:calendar id="fechaFin" mindate="#{utilMB.today}" value="#{periodoController.selected.fechaFin}" title="Fecha Fin" required="true" requiredMessage="Debe establecer una fecha final para el periodo " pattern="dd/MM/yyyy" />
                    <h:outputLabel value="Metodología a aplicar" for="metodologia" />
                    <p:selectOneMenu disabled="#{existenEvaluaciones}" id="metodologia" immediate="true"  value="#{periodoController.metodologia}" >
                        <f:selectItems value="#{periodoController.listaMetodologiasCombo}" var="met"  itemValue="#{met}" itemLabel="#{met}"/>                      
                        <p:ajax  event="change"/>
                    </p:selectOneMenu>
                </h:panelGrid>
                <p:outputPanel id="defPanel"  autoUpdate="true"    >
                    <br/>
                    <p:panel header="Definición  de Metodología por Nivel" style="width: 70%" rendered="#{periodoController.renderDefPanel}">
                        <h:panelGrid columns="2" style="width: 100%" columnClasses="colNivel,colMetod" rules="rows"  >
                            <c:forEach items="#{periodoController.selected.asignacionMetodologiaList}" var="am" varStatus="status" >
                                <h:outputText value="#{am.niveles.descripcion}"/>
                                <p:selectOneButton disabled="#{existenEvaluaciones}" value="#{am.metodologia}" required="true" requiredMessage="Debe seleccionar un tipo de metodologia para el nivel #{am.niveles.descripcion}">
                                    <f:selectItems value="#{periodoController.listaMetodologiasOneButton}" var="metod" itemValue="#{metod}" itemLabel="#{metod}"/>
                                </p:selectOneButton>
                            </c:forEach>
                        </h:panelGrid>
                    </p:panel>                    
                </p:outputPanel>
                <p:remoteCommand action="#{periodoController.update()}" name="guardar" update=":mainForm"/>
              
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/periodo/ListaPeriodos.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://java.sun.com/jsp/jstl/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="Periodos de Evaluación"></h:outputText>
        </ui:define>
        <ui:define name="headerContent">
            <p:commandButton styleClass="floatRight" value="Nuevo periodo" action="#{periodoController.prepareCreate()}" disabled="#{planEstrategicoController.planVigente==null}"/>
        </ui:define>
        <ui:define name="body">
            <c:set var="existePlanVigente" value="#{planEstrategicoController.planVigente!=null}"/>
            <h:form rendered="#{!existePlanVigente}">
                <div class="alert alert-danger lead"> <h:outputText value="No existe un plan vigente, debe existir uno para crear un nuevo periodo de evaluación" /> 
                    <hr/>
                    <p:commandButton styleClass="btn btn-primary" action="/planEstrategico/CrearPlanEstrategico?faces-redirect=true" value="Nuevo Plan Estratégico">                    
                         <f:setPropertyActionListener target="#{utilMB.indexMenu}" value="#{2}" />
                    </p:commandButton></div>
                
            </h:form>
            <h:form id="mainForm"  rendered="#{existePlanVigente}"> 
                    <p:messages autoUpdate="true" id="mensajes" />

                    <p:dataTable var="p" value="#{periodoController.listaPeriodos}" id="ListaPeriodos" emptyMessage="No se han registrado periodos de evaluación">
                            <p:column headerText="Id Periodo">
                                <h:outputText value="#{p.idPeriodo}" />
                            </p:column>

                            <p:column headerText="Descripción">  
                                <h:outputText value="#{p.descripcion}" />  
                            </p:column>  

                            <p:column headerText="Fecha Inicio">  
                                <h:outputText value="#{p.fechaInicio}"> 
                                <f:convertDateTime type="date" pattern="dd-MM-yyyy"/>
                                </h:outputText>  
                            </p:column>  

                            <p:column headerText="Fecha Fin">  
                                <h:outputText value="#{p.fechaFin}" >
                                <f:convertDateTime type="date" pattern="dd-MM-yyyy"/>
                                </h:outputText>  
                            </p:column>  

                            <p:column headerText="Metodologia">  
                                <h:outputText value="#{periodoController.getMetodologiaPeriodo(p)}" />  
                            </p:column>  

                        <p:column>
                            <p:commandButton title="Ver" icon="ui-icon-search" action="#{periodoController.prepareView()}">
                                  <f:setPropertyActionListener value="#{p}" target="#{periodoController.selected}"/>
                               </p:commandButton>
                            <p:commandButton  title="Editar" disabled="#{!periodoController.isEditable(p)}" icon="ui-icon-pencil" action="#{periodoController.prepareUpdate()}">
                                    <f:setPropertyActionListener  value="#{p}" target="#{periodoController.selected}"/>
                               </p:commandButton>
                            <p:commandButton oncomplete="confirmation.show()" disabled="#{!periodoController.isEliminable(p)}" update=":confirmForm" title="#{!periodoController.isEliminable(p)? 'No se puede eliminar porque ya se realizaron evaluaciones en este periodo' : 'Eliminar'}" icon="ui-icon-trash">
                                    <f:setPropertyActionListener value="#{p}" target="#{periodoController.selected}"/>
                               </p:commandButton>
                           </p:column>

                      </p:dataTable>
            </h:form>
            
                    
            
           <p:dialog id="confirmDialog"  header="Confirmacion de Eliminacion" modal="true" widgetVar="confirmation" appendToBody="true" >  
                    <h:form id="confirmForm">
                        <h:outputText value="Seguro que desea eliminar el periodo #{periodoController.selected.idPeriodo}"/>
                         
                         <p:separator/>
                        
                        <p:commandButton ajax="false" id="confirm" update=":mainForm:ListaPeriodos" value="Si" oncomplete="confirmation.hide()"  
                                         actionListener="#{periodoController.performDestroy()}" />  
                        <p:commandButton id="decline" value="No" onclick="confirmation.hide()" type="button" />   
                     </h:form>
               </p:dialog> 
            
            
        </ui:define>
        
        <ui:define name='sidebar'>
            <ui:include src="_sideBarPeriodo.xhtml" />
        </ui:define>
    </ui:composition>

</html>

web/periodo/_sideBarPeriodo.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
             <h:form>         
               <p:menu style="width: 100%">
                <p:submenu label="Acciones">
                    <p:menuitem value="Nuevo periodo de evaluación" action="#{periodoController.prepareCreate()}" icon="ui-icon-plusthick"/> 
                    <p:menuitem value="Lista de Periodos" action="ListaPeriodos?faces-redirect=true" icon="ui-icon-note" /> 
                </p:submenu>
                <p:submenu label="Enlaces relacionados">   
                    <p:menuitem rendered="#{periodoController.hayPeriodoVigente and sessionMB.esEmpleado}" value="Evaluar" action="/evaluacion/SeleccionarEvaluacion?faces-redirect=true" icon="ui-icon-circle-check"> 
                        <f:setPropertyActionListener target="#{utilMB.indexMenu}" value="#{8}" />
                    </p:menuitem> 
                    <p:menuitem value="Reportes" action="/Reportes/ExportacionReportes_1?faces-redirect=true" icon="ui-icon-image" >
                         <f:setPropertyActionListener target="#{utilMB.indexMenu}" value="#{7}" />                                    
                    </p:menuitem>
                </p:submenu>
             </p:menu>
            </h:form>
            
</html>