src/java/uca/sed360/managedBeans/EvaluacionController.java
package uca.sed360.managedBeans;

import java.io.IOException;
import uca.sed360.jpaEntities.Evaluacion;
import uca.sed360.managedBeans.util.JsfUtil;
import uca.sed360.ejbs.EvaluacionFacade;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.application.ConfigurableNavigationHandler;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.SelectItem;
import javax.servlet.http.HttpServletResponse;
import uca.sed360.jpaEntities.Capacitaciones;
import uca.sed360.jpaEntities.Criterio;
import uca.sed360.jpaEntities.Empleados;
import uca.sed360.jpaEntities.Periodo;
import uca.sed360.jpaEntities.PreguntaAbierta;
import uca.sed360.jpaEntities.PreguntaCerrada;
import uca.sed360.jpaEntities.DetallePreguntaCerrada;
import uca.sed360.jpaEntities.Escalas;
import uca.sed360.jpaEntities.Nivel360;
import uca.sed360.jpaEntities.RespuestaPreguntaAbierta;
import uca.sed360.jpaEntities.RespuestaPreguntaAbiertaPK;
import uca.sed360.jpaEntities.RespuestaPreguntaCerrada;
import uca.sed360.jpaEntities.Usuarios;
import uca.sed360.managedBeans.util.reportes.GeneradorDeReportesPDF;
import uca.sed360.managedBeans.util.PromedioEmpleado;

/**
 *
 * @author Estacion 2
 */
@ManagedBean(name = "evaluacionController")
@SessionScoped
public class EvaluacionController implements Serializable {

    @ManagedProperty(value="#{sessionMB}")
    private SessionMB sessionMB;
    @ManagedProperty(value="#{planEstrategicoController}")
    private PlanEstrategicoController planMB;
    @ManagedProperty(value="#{periodoController}")
    private PeriodoController periodoMB;
    @ManagedProperty(value = "#{capacitacionesController}") 
    private CapacitacionesController controladorDeCapacitaciones;
    
    @ManagedProperty(value = "#{auditoriaController}")
    private AuditoriaController audiController;
    
    /**
     * Definición de variables
     */
    
    private boolean evaluadoSeleccionado=false;
    private HashMap indicesRPC,hashMapEvaluados,map;
    private List<RespuestaPreguntaAbierta> listaRespuestasPreguntasAbierta;
    private List<Criterio> listaCriteriosTipoEmpleado;
    private Evaluacion current;
    private List<Empleados> subordinadosEmp;
    private List<Empleados> paresEmp;
    private boolean  vistaHTML=true,metodologiaAsignada360,validadoMetodologiaAsignada360=false,realizadoValidacionesInciales=false;
    private List<Empleados> listaEvaluacionesSubordinados;
    private double puntajeTotal;       
    private String ruta;
    private GeneradorDeReportesPDF pdf;    
    private String nombreRep;
    private Empleados evaluado;
    private Nivel360 nivel;
    private List listaPuntajes;
    private ArrayList<Evaluacion> evaluacionesPendientesFiiltradas;
    private ArrayList<Evaluacion> evaluacionesASubordinadosPendientesFiltradas;
    private List<Object[]> PromediosGlobales;
    private List<PromedioEmpleado> PromediosGlobalesFiltrados;
    private List<Capacitaciones> Capacitaciones;
    private List<Capacitaciones> CapacitacionesSeleccionadas;
    private Periodo periodoEvaluacion;
    private HashMap<String,DetallePreguntaCerrada> detallesMap;
    private List<Evaluacion> listaEvaluaciones,listaEvaluacionesFiltrado;
    private List<Evaluacion> evaluacionesImpresasFiltradas;
    private List<Evaluacion> evaluacionesNoImpresasFiltradas;
    private List<Escalas> escalasOrdenadas;
    
 
    @EJB
    private uca.sed360.ejbs.PreguntaAbiertaFacade ejbPreguntaAbierta;
    @EJB
    private uca.sed360.ejbs.EvaluacionFacade ejbEvaluacion;
    @EJB
    private uca.sed360.ejbs.EmpleadosFacade ejbEmpleados;
    @EJB
    private uca.sed360.ejbs.PeriodoFacade ejbPeriodo;
    @EJB
    private uca.sed360.ejbs.UsuariosFacade ejbUsuarios;
    @EJB
    private uca.sed360.ejbs.CriterioFacade ejbCriterios;
    @EJB
    private uca.sed360.ejbs.AsignacionMetodologiaFacade ejbAsignacionMetodologia;
    @EJB
    private uca.sed360.ejbs.EscalasFacade ejbEscalas;
    

    /**
     *
     */
    public EvaluacionController() {

    }
    //Getter y Setter de los ManagedProperties
    /**
     *
     * @return
     */
    public SessionMB getSessionMB() {
        return sessionMB;
    }

    /**
     *
     * @param sessionMB
     */
    public void setSessionMB(SessionMB sessionMB) {
        this.sessionMB = sessionMB;
    } 

    /**
     *
     * @return
     */
    public PlanEstrategicoController getPlanMB() {
        return planMB;
    }
    
     
    /**
     *
     * @param planMB
     */
    public void setPlanMB(PlanEstrategicoController planMB) {
        this.planMB = planMB;       
    }

    /**
     *
     * @return
     */
    public PeriodoController getPeriodoMB() {
        return periodoMB;
    }

    /**
     *
     * @param periodoMB
     */
    public void setPeriodoMB(PeriodoController periodoMB) {
        this.periodoMB = periodoMB;
    }

    //Lista Criterios tipo Empleado
    /**
     *
     * @return
     */
    public List<Criterio> getListaCriteriosTipoEmpleado() {
        return listaCriteriosTipoEmpleado;
    }

    /**
     *
     * @param listaCriteriosTipoEmpleado
     */
    public void setListaCriteriosTipoEmpleado(List<Criterio> listaCriteriosTipoEmpleado) {
        this.listaCriteriosTipoEmpleado = listaCriteriosTipoEmpleado;
    }
    
    /**
     *
     * @return
     */
    public double getPuntaje(){
        double sum = 0;
        for(Object o:getListaPuntajes()){
            Object[] a = (Object[]) o;
            sum += ((Double)a[4]).doubleValue();
//            System.out.print(a[4]);
        }
        return sum;
    }
//Evaluacion  
    /**
     * devuelve el objeto current a las vistas
     * @return 
     */
    public Evaluacion getSelected() {
        if (current == null) {
            current = new Evaluacion();
        }
        return current;
    }
    
    /**
     *
     * @param evaluacion
     */
    public void setSelected(Evaluacion evaluacion){
        this.current = evaluacion;
    }
    
    /**
     * devuleve true si el empleado en sesion selecciono a otro empleado para evaluar. 
     * Se utiliza como validacion que el empleado termine una evaluacion luego que la haya empezado
     * @return 
     */  
    public boolean isEvaluadoSeleccionado() {
        return evaluadoSeleccionado;
    }

    /**
     *
     * @param evaluadoSeleccionado
     */
    public void setEvaluadoSeleccionado(boolean evaluadoSeleccionado) {
        this.evaluadoSeleccionado = evaluadoSeleccionado;
    }
    /**
     * retorna al empleado evaluado. Se utiliza principalmente cuando se consulta una evaluacion realizada
     * @return 
     */
    public Empleados getEvaluado() {
        return evaluado;
    }

    /**
     *
     * @param evaluado
     */
    public void setEvaluado(Empleados evaluado) {
        this.evaluado = evaluado;
    }

    /**
     *
     * @return
     */
    public HashMap<String, DetallePreguntaCerrada> getDetallesMap() {
        return detallesMap;
    }

    /**
     *
     * @param detallesMap
     */
    public void setDetallesMap(HashMap<String, DetallePreguntaCerrada> detallesMap) {
        this.detallesMap = detallesMap;
    }
    
    /**
     * Este metodo valida si el empleado tiene asignada metodologia 360
     * @return 
     */  
    public boolean isMetodologiaAsignada360() {
         if(validadoMetodologiaAsignada360==false){
                metodologiaAsignada360=ejbAsignacionMetodologia.isMetodologiaAsignada360(periodoMB.getPeriodoVigente(), 
                                                                                       sessionMB.getCurrentUser().getEmpleados().getNivel());                                     
                validadoMetodologiaAsignada360=true;
           }
        return metodologiaAsignada360;
    }

    /**
     *
     * @param metodologiaAsignada360
     */
    public void setMetodologiaAsignada360(boolean metodologiaAsignada360) {
        this.metodologiaAsignada360 = metodologiaAsignada360;
    }

    /**
     *
     * @return
     */
    public boolean isVistaHTML() {
        return vistaHTML;
    }

    /**
     *
     * @param vistaHTML
     */
    public void setVistaHTML(boolean vistaHTML) {
        this.vistaHTML = vistaHTML;
    }
    
     //retorna la informacion del encabezado durante la evaluacion
    /**
     *
     * @return
     */
    public String getInfoEvaluado(){
        if(current.getEvaluado().equals(current.getEvaluador()))
            return "Realizando Autoevaluación";
        else
            return "Usted está evaluando a ".concat(current.getEvaluado().getNombre()).concat("  ").concat(current.getEvaluado().getApellido());
    }
    
    //punto de decision de aplicacion de los instrumentos
    /**
     *
     * @return
     */
    public String inicializarEvaluacion() {
       current.setEvaluador(sessionMB.getCurrentUser().getEmpleados());
       current.setIdPeriodo(periodoEvaluacion);       
       current.setIdEvaluacion(getFacade().generarId( current.getEvaluador(),current.getEvaluado(), current.getIdPeriodo()));   
       current.setRespuestaPreguntaCerradaCollection(new ArrayList<RespuestaPreguntaCerrada>());

web/ponderacion/ListaPonderaciones.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://java.sun.com/jsp/jstl/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="Ponderaciones"></h:outputText>
        </ui:define>
        <ui:define name="sidebar">
            <ui:include src="/ponderacion/_sideBarPonderacion.xhtml"/>
        </ui:define>
        <ui:define name="headerContent">
             <h5><h:outputText value="Seleccione el plan a ponderar:" /></h5>
             <h:form rendered="#{!planEstrategicoController.listaPlanes.isEmpty()}" id="seleccionar" style="margin-bottom: 0">
                 <p:selectOneMenu  value="#{ponderacionController.planAPonderar}" required="true" requiredMessage="Seleccione el plan para ponderar sus correspondientes criterios">
                     <f:selectItems  value="#{planEstrategicoController.listaPlanes}" var="plan" itemValue="#{plan}" itemLabel="#{plan.descripcion}"/>                        
                     <p:ajax update=":mainForm,:formuPonderacion" listener="#{ponderacionController.agregarListaPonderaciones()}"/>
                 </p:selectOneMenu>
             </h:form>
        </ui:define>
        
        
        <ui:define name="body">
            
            <f:metadata>
                <f:event type="preRenderView" listener="#{ponderacionController.preparar()}"/>
            </f:metadata>
            <h:form  id="mainForm"  rendered="#{!planEstrategicoController.listaPlanes.isEmpty()}">                                    
                <p:tabView  value="#{tiposEmpleadoController.listaTiposEmpleado}" var="tipoE">
                    <p:tab title="#{tipoE.descripcion}">
                        
                        <h:outputText styleClass="alert lead" value="Criterios para el tipo de empleado #{tipoE.descripcion}"/> 
                        <p:commandButton update=":formuPonderacion" oncomplete="dialogPonderar.show()" styleClass="floatRight" value="Ponderar">                                
                                <f:setPropertyActionListener value="#{tipoE}" target="#{ponderacionController.tipoEmpleado}"/>
                                <f:setPropertyActionListener target="#{ponderacionController.ponderacionesComprobadas}" value="#{false}"/>
                        </p:commandButton>
                         <br/>
                         <br/>
                        <p:dataTable id="criterios" var="criterio" value="#{ponderacionController.planAPonderar.criteriosCollection}" editable="true" editMode="cell" >                              
                            <f:facet name="header">  
                                Ponderar Instrumentos de Evaluación según los criterios del plan ... 
                            </f:facet>           
                            <c:set var="criterioXtipoE" value="#{criterio.tipoEmpleado.idTipoempleado == tipoE.idTipoempleado}"/>
                            
                            <p:columnGroup type="header">
                                <p:row>
                                    <p:column>
                                        <f:facet name="header">
                                            Criterio
                                        </f:facet>
                                    </p:column>
                                    
                                    <c:forEach items="#{niveles360Controller.listaNiveles360}" var="nivel">
                                        <p:column>
                                            <f:facet name="header">
                                                #{nivel.descripcion}
                                            </f:facet>
                                        </p:column>
                                    </c:forEach>
                                    
                                </p:row>                                
                            </p:columnGroup>
                            
                            <p:column rendered="#{criterioXtipoE}">
                                <h:outputText value="#{criterio.descripcion}" />
                            </p:column>

                    <c:forEach items="#{niveles360Controller.listaNiveles360}" var="n">                    
                        <c:set var="indice" value="#{ponderacionController.indicesDeLasPonderaciones.get(criterio.idCriterio.toString().concat(n.idNivel360.toString()))}"/>
                        <p:column rendered="#{criterio.tipoEmpleado == tipoE}">                       
                                    <h:outputText value="#{criterio.ponderacionCollection.get(indice).puntaje}"/>                                                             
                        </p:column>
                    </c:forEach>                                                                                   

                        </p:dataTable> 
                    </p:tab>                    
             </p:tabView>                
            </h:form>
            
            
            
            
                                                            
            <p:dialog header="Ponderación de los criterios" closable="false" modal="true" appendToBody="true" id="dialogoPonderar" widgetVar="dialogPonderar" resizable="false">
                <h:form id="formuPonderacion">
                <p:remoteCommand name="guardar" actionListener="#{ponderacionController.ponderarCriterios()}"/>
                <p:growl autoUpdate="true" />               
                <p:dataTable editMode="cell" editable="true" value="#{ponderacionController.planAPonderar.criteriosCollection}" var="criterio">                
                    <p:ajax event="cellEdit" listener="#{ponderacionController.comprobarPonderacion()}" update=":mainForm"/>
                    <p:columnGroup type="header">
                        <p:row>
                            <p:column>
                                <f:facet name="header">
                                    <h:outputText value="Criterios"/>
                                </f:facet>
                            </p:column>

                            <c:forEach items="#{niveles360Controller.listaNiveles360}" var="nivel">
                                <p:column headerText="#{nivel.descripcion}"></p:column>
                            </c:forEach>
                        </p:row>
                    </p:columnGroup>

                    <p:column  rendered="#{criterio.tipoEmpleado == ponderacionController.tipoEmpleado}">
                        <h:outputText value="#{criterio.descripcion}"/>
                    </p:column>                                                         
                    <c:forEach items="#{niveles360Controller.listaNiveles360}" var="n">                    
                        <c:set var="indice" value="#{ponderacionController.indicesDeLasPonderaciones.get(criterio.idCriterio.toString().concat(n.idNivel360.toString()))}"/>
                        <p:column  rendered="#{criterio.tipoEmpleado == ponderacionController.tipoEmpleado}">
                            <p:cellEditor>
                                <f:facet name="output">
                                    <h:outputText value="#{criterio.ponderacionCollection.get(indice).puntaje}"/>
                                </f:facet>
                                <f:facet  name="input">
                                    <p:inputText disabled="#{respuestaPreguntaCerradaController.existeRespuestasAPreguntasPorCriterioyNivel(criterio,n)}" value="#{criterio.ponderacionCollection.get(indice).puntaje}"/>
                                </f:facet>
                            </p:cellEditor>
                        </p:column>
                    </c:forEach>
                </p:dataTable>
                <p:commandButton actionListener="#{ponderacionController.ponderarCriterios()}"  value="Guardar" update=":mainForm,:formuPonderacion"/>
                <p:commandButton id="btnExit" rendered="#{ponderacionController.ponderacionesComprobadas}" value="Salir" onclick='formuPonderaciones.hide();'></p:commandButton>
            </h:form>
            </p:dialog>
            
            
            <h:form rendered="#{planEstrategicoController.listaPlanes.isEmpty()}">
             <div class="alert alert-danger lead">  <h:outputText value="No hay planes estrategicos. Es necesario crear un plan estratégico con sus criterios para poder ponderarlos." /> </div>
                <p:commandButton action="/planEstrategico/PlanesEstrategicos?faces-redirect=true" value="Ir a sección de planes estrategicos"  />
             </h:form>       
            
        </ui:define>
    </ui:composition>

</html>

web/ponderacion/Ponderar.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://java.sun.com/jsp/jstl/core">

    <ui:composition template="/template.xhtml">

        <ui:define name="sidebar">
            <ui:include src="/ponderacion/_sideBarPonderacion.xhtml"/>
        </ui:define>
        <ui:define name="headerContent">            
            <h2 class="myLead">Ponderar criterios para el tipo de empleado: #{ponderacionController.tipoEmpleado.descripcion}</h2>
            <p:commandButton styleClass="floatRight"  value="Guardar" type="button" onclick="guardar()"/> 
        </ui:define>
        <ui:define name="body">
                       
        </ui:define>
    </ui:composition>

</html>

web/ponderacion/_sideBarPonderacion.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
             <h:form>         
               <p:menu style="width: 100%">
                
                <p:submenu label="Enlaces Relacionados">
                    <p:menuitem value="Planes Estratégicos" action="/planEstrategico/PlanesEstrategicos?faces-redirect=true" icon="ui-icon-note">
                         <f:setPropertyActionListener target="#{utilMB.indexMenu}" value="#{1}" />
                     </p:menuitem> 
                     <p:menuitem value="Instrumentos" action="/instrumentos/ListaInstrumentos?faces-redirect=true" icon="ui-icon-note">
                         <f:setPropertyActionListener target="#{utilMB.indexMenu}" value="#{3}" />
                     </p:menuitem>
                     <p:menuitem value="Periodos de Evaluación" action="/periodo/ListaPeriodos?faces-redirect=true" icon="ui-icon-note">
                         <f:setPropertyActionListener target="#{utilMB.indexMenu}" value="#{4}" />
                     </p:menuitem> 
                </p:submenu>
             </p:menu>
            </h:form>
            
</html>
