src/java/uca/sed360/managedBeans/PlanEstrategicoController.java
package uca.sed360.managedBeans;

import uca.sed360.jpaEntities.PlanEstrategico;
import uca.sed360.jpaEntities.Criterio;
import uca.sed360.managedBeans.util.JsfUtil;
import uca.sed360.ejbs.PlanEstrategicoFacade;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.SelectItem;
import org.primefaces.event.CellEditEvent;
import uca.sed360.jpaEntities.Escalas;
import uca.sed360.managedBeans.util.reportes.ReportesUtil;
import uca.sed360.jpaEntities.TipoEmpleado;

/**
 * Controlador que maneja los planes estratégicos
 * @author Estacion 2
 */
@ManagedBean(name = "planEstrategicoController")
@SessionScoped
public class PlanEstrategicoController implements Serializable {
    
    private PlanEstrategico current;
    private PlanEstrategico planTemporal;
    private List<PlanEstrategico> listaPlanes;
    private List<Double> valoresDeEscalas ;
    private Criterio newCriterio;
    private ArrayList<Criterio> criteriosNuevosParaEdición;
    private ArrayList<Criterio> criteriosEliminados;
    private Escalas newEscala;
    private boolean escalaNoAPlica,hayEvaluacionesParaElPlanAEditar, validadoHayPlanesEstrategicos=false;
   // private Date today;
    
    @ManagedProperty(value = "#{auditoriaController}")
    private AuditoriaController audiController;
    
    @EJB
    private uca.sed360.ejbs.PlanEstrategicoFacade ejbFacade;
    @EJB
    private uca.sed360.ejbs.EvaluacionFacade ejbEvaluaciones;
    @EJB
    private uca.sed360.ejbs.TiposEmpleadoFacade ejbTipoE;
    private PlanEstrategico planVigente;
    private int posicion;


    /**
     * Constructor
     */
    public PlanEstrategicoController() {
    }
    
    /**
     * Despues de construir el controlador inicializa los objetos que
     * forman parte del plan
     */
    @PostConstruct
        public void init()
        {
                
                valoresDeEscalas = new ArrayList<Double>();
                for(double i = 1;i<=10;i++)
                {   
                    valoresDeEscalas.add(Double.valueOf(i/10));
                }
                setPosicion(1);
                newCriterio = new Criterio();
                newCriterio.setDescripcion("nuevo criterio");
                newEscala = new Escalas();
                newEscala.setDescripcion("nueva escala");
                
                setEscalaNoAPlica(false);
        }
    
    
    //Criterios

    /**
     *
     * @return
     */
    public Criterio getNewCriterio() {
        if(newCriterio==null) {
            newCriterio=new Criterio();
        }
        return newCriterio;
    }

    /**
     *
     * @param criterio
     */
    public void setNewCriterio(Criterio criterio) {
        this.newCriterio = criterio;
    }

   

    /**
     * Anula el plan estratégico
     */
    public void cancelar(){ 
        current=null;    
        newCriterio = null;
        newEscala = null;
        posicion=1;
        escalaNoAPlica = false;
    }
    
    /**
     * Agrega un criterio al plan
     */
    public void agregarCriterio() {
        
        boolean agregado=false;
        for (TipoEmpleado tipoE : ejbTipoE.findAll()) {
            for (Criterio c : current.getCriteriosCollection()) {
                if (c.getTipoEmpleado().getIdTipoempleado() == tipoE.getIdTipoempleado() && newCriterio.getTipoEmpleado().getIdTipoempleado()==tipoE.getIdTipoempleado()) {
                    if (c.getDescripcion().equals(newCriterio.getDescripcion())) {
                        agregado = true;
                        JsfUtil.addErrorMessage("Ya se ha agregado el criterio: <".concat(newCriterio.getDescripcion().concat(">"))
                                + " para el tipo de empleado " + tipoE.getDescripcion());
                        break;
                    }
                }
            }
        }
        
        
        if(agregado==false){            

            
           newCriterio.setPlanEstrategico(current);                                          
           
           current.getCriteriosCollection().add(newCriterio);
           newCriterio= new Criterio();
           newCriterio.setDescripcion("nuevo criterio");           
        }        
    }
    
    
    /**
     * Elimina un criterio del plan
     * @param criterio
     */
    public void quitarCriterio(Criterio criterio) {                                   
        for(int i=0;i<current.getCriteriosCollection().size();i++){                                
            if(current.getCriteriosCollection().get(i).getDescripcion().equals(criterio.getDescripcion())){
                current.getCriteriosCollection().remove(i);
                break;
            }                
        }                
    }    
    
    //Escalas

    /**
     *
     * @return
     */
    public Escalas getNewEscala() {
            if(newEscala == null) {
            newEscala=new Escalas();}
            return newEscala;
    }

    /**
     *
     * @param newEscala
     */
    public void setNewEscala(Escalas newEscala) {
        if(newEscala.getValor() > 1) {
        JsfUtil.addErrorMessage("El valor de la escala no debe ser mayor que 1");
        this.newEscala = null;
        } else
        this.newEscala = newEscala;
    }

    
    /**
     * Agrega la escala de evaluación que será usada en el plan estratégico
     */
    public void agregarEscala() {
        boolean agregado=false;
        
        
        if(newEscala.getValor() > 1 || newEscala.getValor() <= 0) {
        JsfUtil.addErrorMessage("El valor de la escala no debe ser mayor a 1 ni menor a 0");
        } else {
        
        for(Escalas e:current.getEscalasCollection()){
           if(e.getDescripcion().equals(newEscala.getDescripcion())){
               agregado=true;
               JsfUtil.addErrorMessage("Ya se ha agregado la escala: <".concat(newEscala.getDescripcion().concat(">")));
               break;
           }
           
        }
        if(!agregado){
           newEscala.setIdPlanEstrategico(current);
           current.getEscalasCollection().add(newEscala);
           newEscala= new Escalas();
           newEscala.setDescripcion("nueva escala");
        } 
      
    
                
        }
    }
    
    /**
     * Elimina la escala del plan
     * @param escala
     */
    public void quitarEscala(Escalas escala) {
        for(int i=0;i<current.getEscalasCollection().size();i++){
            if(current.getEscalasCollection().get(i).getDescripcion().equals(escala.getDescripcion())){
                current.getEscalasCollection().remove(i);
                break;
            }                
        }
    }
   
    /**
     * Valida que un plan estratégico pueda ser modificado mientras no existan
     * evaluaciones relacionadas a dicho plan
     */
    public void validarEdicionPlan() {
      
        if (ejbEvaluaciones.obtenerEvaluacionesPorPlanEstrategico(current).size() >= 1) {
                 hayEvaluacionesParaElPlanAEditar = true;                           
       } 
   
   }
   
    /**
     * Modifica el criterio en la celda de la vista html para guardar en la BD
     * @param event
     */
    public void onCellEditCriterio(CellEditEvent event) {  
        Criterio oldValue = (Criterio) event.getOldValue();  
        Criterio newValue = (Criterio) event.getNewValue();  
          
        if(newValue != null && !newValue.equals(oldValue)) {  
            JsfUtil.addSuccessMessage("Se ha modificado el criterio "+oldValue.getDescripcion()+" a "+newValue.getDescripcion() );
        }  
    } 
   
    /**
     * Modifica la escala en la celda de la vista html para guardar en la BD
     * @param event
     */
    public void onCellEditEscala(CellEditEvent event) {  
        Escalas oldValue = (Escalas) event.getOldValue();  
        Escalas newValue = (Escalas) event.getNewValue();  
          
        if(newValue != null && !newValue.equals(oldValue)) {  
            JsfUtil.addSuccessMessage("Se ha modificado la escala "+oldValue.getDescripcion());
        }  
    } 
    //Plan Estrategicos
    /**
     *
     * @return
     */
    public PlanEstrategico getPlanVigente() {
        if(planVigente==null)
            planVigente=getFacade().getPlanVigente();
        return planVigente;
    }

    /**
     *
     * @param planVigente
     */
    public void setPlanVigente(PlanEstrategico planVigente) {
        this.planVigente = planVigente;
    }
  
    /**
     * Busca en la base de datos el plan estratégico anterior o el último
     * @return plan estratégico si existe
     */
    public PlanEstrategico getLastPlan(){
        int listaPlanesSize=getListaPlanes().size();
        if(listaPlanesSize>0)
            return getListaPlanes().get(listaPlanesSize-1);
        return null;
    }
    
    /**
     * Busca en la base de datos el primer plan estratégico
     * @return plan estratégico si existe
     */
    public PlanEstrategico getPrimerPlan(){
        if(getListaPlanes().size() > 0)
            return getListaPlanes().get(0);
        else
            return null;
    }

    /**
     *
     * @return
     */
    public PlanEstrategico getCurrent() {
        if (current == null) {
            current = new PlanEstrategico();
        }
        return current;
    }

    /**
     *

src/java/uca/sed360/managedBeans/RolesController.java
package uca.sed360.managedBeans;

import uca.sed360.jpaEntities.Roles;
import uca.sed360.managedBeans.util.JsfUtil;
import uca.sed360.ejbs.RolesFacade;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.SelectItem;

/**
 * Controlador que maneja los roles o permisos del usuario en el sistema SED360
 * @author Estacion 2
 */
@ManagedBean(name = "rolesController")
@SessionScoped
public class RolesController implements Serializable {

    private Roles current;
    private List<Roles> listaRoles,listaRolesParaNoEmpleados,listaRolesParaEmpleados;
    private boolean validadoRoles=false;
    @EJB
    private uca.sed360.ejbs.RolesFacade ejbFacade;

    /**
     * Constructor
     */
    public RolesController() {
    }

    /**
     * 
     * @return
     */
    public Roles getSelected() {
        if (current == null) {
        }
        return current;
    }

    private RolesFacade getFacade() {
        return ejbFacade;
    }

    /**
     *
     * @return
     */
    public List<Roles> getListaRoles() {
        if(listaRoles==null)
            listaRoles=getFacade().findAll();
        return listaRoles;
    }

    /**
     *
     * @param listaRoles
     */
    public void setListaRoles(List<Roles> listaRoles) {
        this.listaRoles = listaRoles;
    }
    
    /**
     *
     */
    public void validarRoles(){
        if(!validadoRoles){
            getFacade().validarRolesEnBD();
            validadoRoles=true;
        }
    }

    /**
     *
     * @return
     */
    public List<Roles> getListaRolesParaEmpleados() {
         if(listaRolesParaEmpleados==null){
              listaRolesParaEmpleados=new ArrayList<Roles>();
              listaRolesParaEmpleados.add(getFacade().find(Roles.ROL_COLABORADOR));
        }
        return listaRolesParaEmpleados;
    }

    /**
     *
     * @param listaRolesParaEmpleados
     */
    public void setListaRolesParaEmpleados(List<Roles> listaRolesParaEmpleados) {
        this.listaRolesParaEmpleados = listaRolesParaEmpleados;
    }
    
    

    /**
     *
     * @return
     */
    public List<Roles> getListaRolesParaNoEmpleados() {
        if(listaRolesParaNoEmpleados==null){
              listaRolesParaNoEmpleados=new ArrayList<Roles>();
              listaRolesParaNoEmpleados.add(getFacade().find(Roles.ROL_CONSULTOR));
              listaRolesParaNoEmpleados.add(getFacade().find(Roles.ROL_ADMINISTRADOR));
        }
        return listaRolesParaNoEmpleados;
    }

    /**
     *
     * @param listaRolesForNonEmployee
     */
    public void setListaRolesParaNoEmpleados(List<Roles> listaRolesForNonEmployee) {
        this.listaRolesParaNoEmpleados = listaRolesForNonEmployee;
    }
    
    
    /**
     *
     * @return
     */
    public String prepareList() {
        return "List";
    }

    /**
     *
     * @return
     */
    public String prepareView() {
        return "View";
    }

    /**
     *
     * @return
     */
    public String prepareCreate() {
        current = new Roles();
        return "Create";
    }
    
    /**
     *
     * @return
     */
    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("RolesCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    /**
     *
     * @return
     */
    public String prepareEdit() {
        return "Edit";
    }

    /**
     *
     * @return
     */
    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("RolesUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    /**
     *
     * @return
     */
    public String destroy() {
        performDestroy();
        return "List";
    }


    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("RolesDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }


   
    /**
     *
     * @return
     */
    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    /**
     *
     * @return
     */
    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }
    
    
    
    
    
    
    
    
    /* 
     * Convertidor de la clase Rol. Este "Faces Converter permitira hacer la
     * conversión de un objeto a su representación cadena y viceversa cuando
     * se trabaja con objetos de tipo "Roles"
     */    
    
    /**
     *
     */
    @FacesConverter(forClass = Roles.class,value = "rolesConverter")
    public static class RolesControllerConverter implements Converter {

        /**
         *
         * @param facesContext
         * @param component
         * @param value
         * @return
         */
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            RolesController controller = (RolesController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "rolesController");
            return controller.ejbFacade.find(getKey(value));
        }       
        
        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }
      
        /*Este método se asegura de que 
         el id del objeto de tipo Roles sea convertido a un 
         string para representar al objeto*/
        String getStringKey(java.lang.Integer value) {
            StringBuffer sb = new StringBuffer();
            sb.append(value);
            return sb.toString();
        }
        

        /*
        Este método regresa el valor del id del objeto como una cadena de 
        * texto para representar a dicho objeto
        */       
        /**
         *
         * @param facesContext
         * @param component
         * @param object
         * @return
         */
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Roles) {
                Roles o = (Roles) object;
                return getStringKey(o.getIdRol());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Roles.class.getName());
            }
        }
    }
}

web/ErrorAutorizacion.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <link rel="shortcut icon" href="resources/img/favicon.ico" />
        <title>Error de Autorizacion</title>
        <h:outputStylesheet name="css/style.css"/>
        <h:outputStylesheet name="css/bootstrap.min.css"/>
    </h:head>
    <h:body>
        <div class="alert alert-error">
            <h4>Error de Autenticacion</h4> 
       
            
       <h:panelGroup  >  
            <h:outputText value="Lo sentimos, no se ha podido comprobar sus privilegios dentro del sistema" />
           
        </h:panelGroup>
        
        </div>
        
        <div class="row-fluid" >
            <div class="span6" style="vertical-align: middle; margin-top: 10%">
 
                <h3 style=" text-align: justify;">Si el problema persiste. Favor acudir a Recursos Humanos o ponerse en contacto con el administrador del sistema.</h3>
            </div>
            
            <div class="span6" align="right" >
                <h:graphicImage value="/resources/img/soporte.png" /> 
            </div>         
        
        </div>
    </h:body>
</html>

web/Index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./template.xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core">

    <ui:define name="title">
        Bienvenido (a) al Sistema de Evaluación del Desempeño
    </ui:define>

    <ui:define name="sidebar">
              <h:form>         
               <p:menu style="width: 100%">
                <p:submenu label="Ayuda">                           
                    <p:menuitem value="Consultar Manual de Usuario" url="#" />             
                </p:submenu>
             </p:menu>
            </h:form>
    </ui:define>

    <ui:define name="body"> 
      <h:form>
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span12">
                     <p:panel header="Información rápida"  >         
                        <p:outputPanel id="periodoVigentePanel" rendered="#{periodoController.hayPeriodoVigente}" >
                              <div class="alert alert-block"> 
                                  <p><b>Hay un Periodo Vigente!</b> El periodo #{periodoController.periodoVigente.idPeriodo} ha entrado en vigencia.</p>
                                  <p>
                                      <li>
                                         Las evaluaciones estan habilidadas para los trabajadores (as)
                                      </li>

                                      <li>
                                          Puede dar seguimiento al proceso de evaluación desde el siguiente  <p:commandLink  action="/Reportes/informacionGeneral?faces-redirect=true" value="enlace">
                                                <f:setPropertyActionListener target="#{utilMB.indexMenu}" value="#{8}" />  
                                                <f:setPropertyActionListener target="#{reportesMB.opcion}" value="#{0}"/>
                                          </p:commandLink>
                                      </li>
                                  </p>
                              </div>
                        </p:outputPanel>

                        <p:outputPanel id="panel" rendered="#{homePageController.tiempoRestanteProximoPeriodo > 0}">  
                             <div class="alert alert-info"> 
                              Quedan <b>#{homePageController.tiempoRestanteProximoPeriodo} dias</b>  para el próximo periodo de evaluación
                              </div>
                        </p:outputPanel> 
                        <p:outputPanel rendered="#{!(homePageController.tiempoRestanteProximoPeriodo > 0) and !periodoController.hayPeriodoVigente}">  
                             <div class="alert alert-info"> 
                                 <ul>
                                     <li>No hay periodo de evaluacion vigente</li>
                                     <li>No hay periodos de evaluacion programados</li>
                                 </ul>

                              </div>
                        </p:outputPanel> 
                    </p:panel>                       
                </div>                           
            </div>
            <br/>
            <div class="row-fluid">
                 <div class="span4">
                     <p:panel header="Planes Estratégicos" >
                         <p class="TextoMenuInicio" style="text-align: justify">Gestione planes estratégicos así como criterios y escalas de evaluación asociados a cada plan.</p>
                         <h:commandButton styleClass="btn btn-info" value="Ir a Planes Estratégicos" action="/planEstrategico/PlanesEstrategicos?faces-redirect=true"/>
                     </p:panel>
                 </div>
                 <div class="span4">
                      <p:panel header="Ponderaciones" >
                         <p class="TextoMenuInicio" style="text-align: justify">Pondere criterios de evaluación de cada tipo de trabajador según los niveles de la metodología 360º.</p>
                         <h:commandButton styleClass="btn btn-info" value="Ir a Ponderaciones" action="/ponderacion/ListaPonderaciones?faces-redirect=true">
                             <f:setPropertyActionListener target="#{ponderacionController.planAPonderar}" value="#{planEstrategicoController.lastPlan}"/>
                         </h:commandButton>
                      </p:panel>
                 </div>   
                <div class="span4">
                      <p:panel header="Definición de Instrumentos" >
                         <p class="TextoMenuInicio" style="text-align: justify">Defina los instrumentos de evaluación para cada tipo de trabajador.</p>
                          <h:commandButton styleClass="btn btn-info" value="Ir a Definición de Instrumentos" action="/instrumentos/ListaInstrumentos?faces-redirect=true"/>
                      </p:panel>
                 </div>                  
             </div>  
            <br/>
             <div class="row-fluid">
                 <div class="span4">
                     <p:panel header="Capacitaciones" >
                        <p class="TextoMenuInicio" style="text-align: justify">Administre el catálogo de capacitaciones que los trabajadores pueden recomendar</p>
                        <h:commandButton styleClass="btn btn-info" value="Ir a Capacitaciones" action="/capacitaciones/ListaCapacitaciones?faces-redirect=true"/>
                     </p:panel>
                 </div>
                 <div class="span4">
                      <p:panel header="Periodos de Evaluación" >
                            <p class="TextoMenuInicio" style="text-align: justify">Administre los periodos de evaluación para que habilitar/deshabilitar las evaluaciónes</p>
                            <h:commandButton styleClass="btn btn-info" value="Ir a Periodos de Evaluación" action="/periodo/ListaPeriodos?faces-redirect=true"/>
                      </p:panel>
                 </div>   
                <div class="span4">
                      <p:panel header="Gestión de Trabajadores" >
                        <p class="TextoMenuInicio" style="text-align: justify">Registre nuevos trabajadores o consulte, edite o de de baja los existentes </p>
                        <h:commandButton styleClass="btn btn-info" value="Ir a Gestión de Trabajadores" action="/empleados/ListaEmpleados?faces-redirect=true"/>
                      </p:panel>                       
                 </div> 
             </div>
             <br/>
             <div class="row-fluid">
                 <div class="span4">
                     <p:panel header="Gestión de Usuarios" >
                        <p class="TextoMenuInicio" style="text-align: justify">Administre los usuarios existentes o cree nuevos usuarios para que tengan acceso al sistema. </p>
                        <h:commandButton styleClass="btn btn-info" value="Ir a Gestión de Usuarios" action="/usuarios/ListaUsuarios?faces-redirect=true"/>
                     </p:panel>
                 </div>
                 <div class="span4">
                      <p:panel header="Consulta de Reportes" >
                        <p class="TextoMenuInicio" style="text-align: justify">Consulte reportes del proceso en tiempo real y reportes de resultados finales por cada periodo</p>
                        <h:commandButton styleClass="btn btn-info" value="Ir a Reportes" action="/Reportes/ReportesAdministracion?faces-redirect=true"/>
                      </p:panel>
                 </div>   
                <div class="span4">
                      <p:panel header="Otros Catálogos" >
                        <p class="TextoMenuInicio" style="text-align: justify">Administre catálogos del sistema como centros de costos, ubicaciones, niveles de trabajador, entre otros.</p>
                        <h:commandButton styleClass="btn btn-info" value="Gestionar Catálogos" action="/instrumentos/ListaInstrumentos?faces-redirect=true"/>
                      </p:panel>
                 </div> 
             </div>  
        </div>
        
        <hr/>
      </h:form>
    </ui:define>

</ui:composition>

web/Reportes.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./../WEB-INF/PlantillaEvaluacion.xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:c="http://java.sun.com/jsp/jstl/core">
    


    <ui:define name="title">
        Evaluaciones
    </ui:define>

    <ui:define name="top">
        <h:outputText value="Usted esta evaluando a #{evaluacionController.selected.evaluado.nombre} #{evaluacionController.selected.evaluado.apellido}" />
        <f:metadata>
            <f:event type="preRenderView" listener="#{evaluacionController.preRenderRealizarEvaluacion()}" />
       </f:metadata>
    </ui:define>
    <ui:define name="content">
  
      
    </ui:define>
 
</ui:composition>